Toreview
TheSpaceSheep/curriculum pull request #3
Opened 2022-05-02 13:34 UTC by TheSpaceSheep

setup the curriculum training
implement a masking game
delete unused chunks of code
reorganise a bit
set up basic unit testing

notes :
 the "DiffLoss" class in losses.py was the orignal loss, I just moved it from the main file to this file

2022-05-02 15:32 UTC, pmichel31415 requested changes
Good work! I left a few comments on things that can be improved. In particular I left some comments on alternate ways to do the masking which should be a bit faster

2022-05-02 15:32 UTC, pmichel31415 commented on egg/core/trainers.py
> +from egg.zoo.compo_vs_generalization.data import mask_attributes
You are not using this

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/train.py
> +        train, validation = ScaledDataset(train, 1), ScaledDataset(train, 1)
Validation is the same as train here

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +            **kwargs
It is probably better to have your underlying game be an argument that you instantiate before wrapping with `GraduallyRevealAttributes`. It will be more modular and the list of arguments to both games will be better annotated.

```python
class GraduallyRevealAttributes(nn.Module):

    def __init__(self,
            game: SenderReceiverRnnReinforce,
            n_attributes: int,
            n_values: int,
        ):
        self.n_attributes = n_attributes
        self.n_values = n_values
        self.game = game

[...]

referential_game = SenderReceiverRnnReinforce(...)
game = GraduallyRevealAttributes(referential_game, ...)
```

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +        idx = torch.tensor(range(self.curriculum_level, self.n_attributes), dtype=torch.long)
You can replace this whole line with

```python
idx = torch.arange(self.curriculum_level, self.n_attributes).to(sender_input.device)
```

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +        idx = torch.tensor(range(self.curriculum_level, self.n_attributes), dtype=torch.long)
Also, you should use a more descriptive variable name like "idxs_to_mask" or something similar

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +        sender_input = mask_attributes(sender_input, idx, self.n_attributes, self.n_values)
You could do this with 

### Same mask for each batch element

```python
# idx is a [n_attributes - curriculum_level] sized 1D tensor
idxs_to_mask = torch.arange(self.curriculum_level, self.n_attributes).to(sender_input.device)
# Replace all elements at indices idxs_to_mask with 0
masked_sender_input = sender_input.index_fill(dim=1, index=idxs_to_mask, value=0)
```

### Different mask for each batch element

(check this on an example first)

```python
# All attributes can be masked equiprobably
mask_probability = torch.ones(self.n_attributes) / self.n_attributes
# idx is a batch_size x [n_attributes - curriculum_level]  sized tensor, sampled w/o replacement
idxs_to_mask = torch.multinomial(mask_probability, self.n_attributes - self.curriculum_level, replacement=False)
# Reshape for broadcasting on the last dimension of the one hot vectors
idxs_to_mask = idxs_to_mask.unsqueeze(-1).repeat(1, 1, sender_input.size(-1))
# Replace all elements at indices idxs_to_mask with 0
masked_sender_input = sender_input.scatter(dim=1, index=idxs_to_mask, src=0)
```

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/losses.py
> +class DiffLoss(torch.nn.Module):
Is this copied from the original implementation?

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +        self.curriculum_level = 1
It would be better to use a more descriptive name, eg. `n_unmasked_idxs` for example. This should also probably be passed as a parameter (eg. `initial_n_unmasked_idxs`)

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +    def update_curriculum_level(self):
You can add a quick docstring to this. Also, might be helpful in the future to be able to set the level directly (rather than by increment)

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_trainer.py
> +        acc_threshold: int=0.99,
annotate as float.

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_trainer.py
> +class CurriculumTrainer(Trainer):
As discussed offline, this could be handled by the generic trainer using callbacks, but we can leave that for later

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_trainer.py
> +        acc_threshold: int=0.99,
How about having this as an optional parameter (can be `None`) so you can run experiments without the curriculum?

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/data.py
> +def mask_attributes(sender_input, idx, n_attributes, n_values, remove_masked_data=False):
See my earlier comments, this can be done much more efficiently in a few lines with some pytorch magic

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +        self.loss.mask_idx = idx
Passing information to the loss via object attribute is not always a good idea (what if you change this value somewhere else by mistake). I would suggest passing the mask idxs by adding them to `aux_input` (which can be a dictionary):

```python
if aux_input is None:
    aux_input = {}
aux_input["mask_idxs"] = idx
```

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +        self.loss.mask_idx = idx
Then you can retrieve the masks from aux_input in the loss function

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/losses.py
> +        self.n_values = n_values
Note that wherever this is needed, you can infer these quantities from sender_input so you don't need to explicitly make them attributes of this class

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/losses.py
> +        ).float()
Same remark

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/losses.py
> +        ).float()
Also the original code is horribly commented, feel free to add more comments to explain what you are doing (for instance what acc and acc_or refer to)

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/losses.py
> +            F.cross_entropy(masked_output, labels, reduction="none")
You can *probably* use F.nll_loss which would be slightly cleaner

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/train.py
> +        train, test = split_train_test(full_data, 0.1)
You should probably introduce a validation set here as well

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/train.py
> +            acc_threshold=0.7,
This should ideally be declared as a command line argument

2022-05-02 15:32 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/unit_tests.py
> +import torch
FYI if you want to make more principled unit tests, python has a good library for it: https://docs.python.org/3/library/unittest.html#basic-example

If you end up using it down the line (not strictly necessary for this PR), we can even setup automated testing on github

2022-05-03 09:43 UTC, TheSpaceSheep commented on egg/zoo/compo_vs_generalization/curriculum_trainer.py
> +        acc_threshold: int=0.99,
I think the command line flag --curriculum serves this purpose by switching between the curriculum trainer and the regular trainer

2022-05-03 09:50 UTC, TheSpaceSheep commented on egg/zoo/compo_vs_generalization/losses.py
> +        self.n_values = n_values
sender_input has shape (batch_size, n_attributes*n_values) so there can be ambiguity

2022-05-03 11:56 UTC, TheSpaceSheep commented on egg/zoo/compo_vs_generalization/losses.py
> +            F.cross_entropy(masked_output, labels, reduction="none")
the receiver's output is not softmaxed, and i believe pytorch's cross_entropy acts as softmax + nll

2022-05-03 13:20 UTC, pmichel31415 requested changes
LGTM, just one bug and a few remaining comments esp. regarding command line arguments

2022-05-03 13:20 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +                    self.n_attributes - self.n_values,
I think this should be n_unmasked_idxs and not n_values

2022-05-03 13:20 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/data.py
> +    mask = mask.scatter(dim=1, index=idxs_to_mask, src=torch.zeros_like(idxs_to_mask, dtype=torch.float32))
I think `src=0`also works

2022-05-03 13:20 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/losses.py
> +        self.n_values = n_values
If so, it would be better for it to be shaped as (batch_size, n_attributes, n_values) and only flatten the last two dimensions where explicitly needed. (1) this will make it easy to infer n_attr/n_val from input without passing it through all the functions and (2) it might help avoid bugs

2022-05-03 13:20 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/losses.py
> +            F.cross_entropy(masked_output, labels, reduction="none")
Oh OK, that's surprising, but good point

2022-05-03 13:20 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/train.py
> +                mode='random'
This and `initial_n_unmasked` should be command line arguments

2022-05-03 13:20 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/train.py
> +        )
You can save up some space by defining this before the if/else block and reusing it with the wrapper when you are doing the curriculum

2022-05-03 13:20 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/train.py
> -    early_stopper = EarlyStopperAccuracy(opts.early_stopping_thr, validation=True)
Any reason you are not using the early stopper? I imagine it's because it won't play well with the curriculum?

2022-05-03 13:20 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +                              "either 'left_to_right' or 'random'")
Protip: you can do something like 

```python
f"mode should be in {valid_modes}"
```

this way you won't have to update the error message every time you add a new mode

2022-05-03 13:20 UTC, pmichel31415 commented on egg/zoo/compo_vs_generalization/curriculum_games.py
> +    the next attribute is revealed, until all attributes are visible.
This doesn't cover random attribute masks

2022-05-03 16:43 UTC, TheSpaceSheep commented on egg/zoo/compo_vs_generalization/train.py
> -    early_stopper = EarlyStopperAccuracy(opts.early_stopping_thr, validation=True)
Yes, for example when only 1 attribute is unmasked, accuracy goes to 1, and the training is immediately interrupted by the early_stopper, although we would like it to continue with the next curriculum task.

2022-05-03 16:44 UTC, TheSpaceSheep commented on egg/zoo/compo_vs_generalization/data.py
> +    mask = mask.scatter(dim=1, index=idxs_to_mask, src=torch.zeros_like(idxs_to_mask, dtype=torch.float32))
There is an issue with scatter doc : src can only take tensors, and there is a hidden parameter called "value" which can take a float. (I think in an earlier version of pytorch, src=0. used to work).
The problem is discussed here https://discuss.pytorch.org/t/torch-scatter-with-scalar-src-works-differently-parameter-name-specified-not-specified/149052

2022-05-18 06:20 UTC, pmichel31415 approved these changes
LGTM!

2022-05-18 12:04 UTC, merged